server:
  port: 9004

spring:
  application:
    name: jeomo-flashSale
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password:
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5  # 初始连接池大小
      min-idle: 5 # 最小空闲连接池大小
      max-active: 500 # 最大连接池大小
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

  redis:
    host: localhost
    password:
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.jeomo.*.domain.entity
  type-enums-package: com.jeomo.flashSale.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
