server:
  port: 8001

spring:
  application:
    name: jeomo-bonus
  jackson:
    defaultPropertyInclusion: NON_EMPTY
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

eureka:
  instance:
    instance-id: jeomo-mem-9001
    prefer-ip-address: true
  client:
    register-with-eureka: false #消费端不用注册到注册服务器上
    fetch-registry: true #获取eureka服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka

ribbon:
  ReadTimeout: 5000 # 设置读取资源最大时间
  ConnectTimeOut: 5000 # 设置连接最大时间
logging:
  level:
    com.jeomo.mem.intf.feign.MemberFeignService: debug # 设置feign日志级别
