server:
  port: 8001

spring:
  application:
    name: jeomo-bonus
  jackson:
    defaultPropertyInclusion: NON_EMPTY
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719

logging:
  level:
    com.jeomo.mem.intf.feign.MemberFeignService: debug # 设置feign日志级别

feign:
  sentinel:
    enabled: true #开启openfeign

ribbon:
  eager-load:
    enabled: true #开启饿加载模式，防止首次加载超时
  ReadTimeout: 6000
  ConnectionTimeout: 6000

