server:
  port: 11111

spring:
  application:
    name: jeomo-shiro-service
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:com.jeomo.*.mapper/*.xml
  type-aliases-package: com.jeomo.*.entity
  type-enums-package: com.jeomo.*.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

logging:
  level:
    org:
      springframework: debug
