server:
  port: 8800

spring:
  application:
    name: jeomo

### 使用前后端分离架构 这里不要配置模板
#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .html

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://qbt.91biz.com.cn:3309/jeomo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: 123456
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

  freemarker:
    template-loader-path: classpath:/templates/
    prefer-file-system-access: false
    settings:
      template_update_delay: 0
      classic_compatible: true
      number_format: 0.######
      template_exception_handler: ignore
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
##### redis 配置 #####
  redis:
    database: 0  # redis 数据库索引（默认为0）
    host: qbt.91biz.com.cn
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数
        max-wait: -1  # 最大阻塞时间(负值表示不限制)
        max-idle: 8 # 最大空闲连接

mem:
  service:
    version: 1.0.0

dubbo:
  scan:
    base-packages: com.jeomo
  application:
    name: jeomo-web
    id: jeomo-web
  protocol:
    id: dubbo
    name: dubbo
    port: 11111
    status: server


  registry:
    id: zookeeper
    address: zookeeper://qbt.91biz.com.cn:2181
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: com.jeomo.*.entity
