spring:
  profiles:
    active: dev
  application:
    name: jeomo-mem
    title: 久萌会员服务
    author: 久萌
    author-url: www.jiumeng.com
    email: jiumemg@jiu.com
    description: 久萌会员服务
  jackson:
    defaultPropertyInclusion: NON_EMPTY
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000



  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10 #消费者初始化值
        max-concurrency: 10 #最大消费者值
        prefetch: 5 #每个消费者拉取的消息数量
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

mybatis-plus:
  mapper-locations: classpath:com.jeomo.*.mapper/*.xml
  type-aliases-package: com.jeomo.*.entity
  type-enums-package: com.jeomo.*.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


member:
  register:
    queue:
      name: member.register.queue
    exchange:
      name: member.register.exchange

log:
  member:
    queue:
      name: log.member.queue.name
    exchange:
      name: log.member.exchange.name
    routing:
      key:
        name: log.member.routing.key.name

mem:
  service:
    version: 1.0.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
