server:
  port: 9002
  dataCenterId: 1 #雪花算法数据中心ID
  machineId: 1 #雪花算法机器ID

spring:
  application:
    name: jeomo-mem
  jackson:
    defaultPropertyInclusion: NON_EMPTY
  redis:
    host: localhost
    port: 6379


  mvc:
    view:
      prefix: /templates/
      suffix: .html

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        concurrency: 10 #消费者初始化值
        max-concurrency: 10 #最大消费者值
        prefetch: 5 #每个消费者拉取的消息数量

mybatis-plus:
  mapper-locations: classpath:com.jeomo.*.mapper/*.xml
  type-aliases-package: com.jeomo.*.entity
  type-enums-package: com.jeomo.*.enums
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    
    

member:
  register:
    queue:
      name: member.register.queue
    exchange:
      name: member.register.exchange

log:
  member:
    queue:
      name: log.member.queue.name
    exchange:
      name: log.member.exchange.name
    routing:
      key:
        name: log.member.routing.key.name

mem:
  service:
    version: 1.0.0

