server:
  port: 9002

spring:
  application:
    name: jeomo-mem

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      url: jdbc:p6spy:mysql://localhost:3306/jeomo?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password:
      validation-query: select 'X'
      min-evictable-idle-time-millis: 300000
      initial-size: 5
      min-idle: 5
      max-active: 500
      max-wait: 60000
      time-between-eviction-runs-millis: 60000

mem:
  service:
    version: 1.0.0

