server:
  port: 9001
  dataCenterId: 1 #雪花算法数据中心ID
  machineId: 1 #雪花算法机器ID

spring:
  flyway:
    enabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 验证错误时 是否自动清除数据库 高危操作!
    clean-on-validation-error: false
    clean-disabled: true


eureka:

