server:
  port: 9527
  
spring:
  application:
    name: jeomo-gateway
  cloud:
    gateway:
      routes:
      - id: mem-route
        uri: http://localhost:9001
        predicates:
        - Path=/mem/test/*
      

eureka:
  instance:
    instance-id: jeomo-gateway #实例名称
    prefer-ip-address: true #显示IP
  client:
    register-with-eureka: true #使用eureka注册
    fetch-registry: true #获取eureka服务列表
    service-url:
      defaultZone: http://localhost:7001/eureka
      
      
# gateway 配置

